name: PyVCG CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cvc5 coverage pylint pycodestyle
    - name: Style check
      run: |
        python -m pycodestyle pyvcg tests
    - name: Lint
      run: |
        python -m pylint --rcfile=pylint3.cfg pyvcg --reports=no --score=no --extension-pkg-allow-list=cvc5
    - name: Test
      run: |
        coverage run --branch --rcfile=coverage.cfg -m unittest discover -s tests -v
        coverage report --rcfile=coverage.cfg --fail-under=100
