name: PyVCG CI (Test, Python 3.9)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: supplypike/setup-bin@v3
        with:
          uri: 'https://github.com/cvc5/cvc5/releases/download/cvc5-1.0.8/cvc5-Linux'
          name: 'cvc5'
          version: '1.0.8'
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: |
          coverage run --branch --rcfile=coverage.cfg -m unittest discover -s tests -v
          coverage report --rcfile=coverage.cfg --fail-under=100
